// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {queue} from '../models';
import {downloader} from '../models';
import {main} from '../models';

export function AddQueueTasks(arg1:Array<string>):Promise<queue.EnqueueReport>;

export function CancelBatch():Promise<void>;

export function CancelQueueTask(arg1:string):Promise<void>;

export function ClearFinishedTasks(arg1:string):Promise<void>;

export function CopyFile(arg1:string,arg2:string):Promise<void>;

export function DetectURL(arg1:string):Promise<string>;

export function DownloadBGM(arg1:Array<string>,arg2:string,arg3:string):Promise<string>;

export function DownloadBGMStandalone(arg1:Array<string>,arg2:string):Promise<string>;

export function DownloadSocial(arg1:string):Promise<downloader.Post>;

export function EnqueueInpaint(arg1:string,arg2:string,arg3:main.TaskParams,arg4:string):Promise<queue.BatchTask>;

export function ExportSourceZip(arg1:string):Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetBGMAudio(arg1:Array<string>,arg2:string):Promise<string>;

export function GetDouyinCookie():Promise<string>;

export function GetEngineStatus():Promise<Record<string, string>>;

export function GetImageBase64(arg1:string,arg2:number):Promise<string>;

export function GetThumb(arg1:string,arg2:number):Promise<main.ThumbInfo>;

export function ListImages(arg1:string):Promise<Array<string>>;

export function ListQueueTasks():Promise<Array<queue.BatchTask>>;

export function PickDirectory():Promise<string>;

export function PickSaveFile(arg1:string):Promise<string>;

export function PrepareSubset(arg1:Array<string>):Promise<string>;

export function RemoveQueueTask(arg1:string):Promise<void>;

export function RetryQueueTask(arg1:string):Promise<void>;

export function SetDouyinCookie(arg1:string):Promise<void>;

export function StartBatch(arg1:string,arg2:string,arg3:main.TaskParams,arg4:string):Promise<queue.BatchTask>;

export function ZipDirectory(arg1:string):Promise<string>;
