// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {downloader} from '../models';
import {main} from '../models';

export function CancelBatch():Promise<void>;

export function CopyFile(arg1:string,arg2:string):Promise<void>;

export function DetectURL(arg1:string):Promise<string>;

export function DownloadSocial(arg1:string):Promise<downloader.Post>;

export function ExportSourceZip(arg1:string):Promise<string>;

export function GetDouyinCookie():Promise<string>;

export function GetEngineStatus():Promise<Record<string, string>>;

export function GetImageBase64(arg1:string,arg2:number):Promise<string>;

export function GetThumb(arg1:string,arg2:number):Promise<main.ThumbInfo>;

export function ListImages(arg1:string):Promise<Array<string>>;

export function PickDirectory():Promise<string>;

export function PickSaveFile(arg1:string):Promise<string>;

export function PrepareSubset(arg1:Array<string>):Promise<string>;

export function SetDouyinCookie(arg1:string):Promise<void>;

export function StartBatch(arg1:string,arg2:string,arg3:main.TaskParams):Promise<void>;

export function ZipDirectory(arg1:string):Promise<string>;
