// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddQueueTasks(arg1) {
  return window['go']['main']['App']['AddQueueTasks'](arg1);
}

export function CancelBatch() {
  return window['go']['main']['App']['CancelBatch']();
}

export function CancelQueueTask(arg1) {
  return window['go']['main']['App']['CancelQueueTask'](arg1);
}

export function ClearFinishedTasks(arg1) {
  return window['go']['main']['App']['ClearFinishedTasks'](arg1);
}

export function CopyFile(arg1, arg2) {
  return window['go']['main']['App']['CopyFile'](arg1, arg2);
}

export function DetectURL(arg1) {
  return window['go']['main']['App']['DetectURL'](arg1);
}

export function DownloadBGM(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadBGM'](arg1, arg2, arg3);
}

export function DownloadBGMStandalone(arg1, arg2) {
  return window['go']['main']['App']['DownloadBGMStandalone'](arg1, arg2);
}

export function DownloadSocial(arg1) {
  return window['go']['main']['App']['DownloadSocial'](arg1);
}

export function EnqueueInpaint(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EnqueueInpaint'](arg1, arg2, arg3, arg4);
}

export function ExportSourceZip(arg1) {
  return window['go']['main']['App']['ExportSourceZip'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetBGMAudio(arg1, arg2) {
  return window['go']['main']['App']['GetBGMAudio'](arg1, arg2);
}

export function GetDouyinCookie() {
  return window['go']['main']['App']['GetDouyinCookie']();
}

export function GetEngineStatus() {
  return window['go']['main']['App']['GetEngineStatus']();
}

export function GetImageBase64(arg1, arg2) {
  return window['go']['main']['App']['GetImageBase64'](arg1, arg2);
}

export function GetThumb(arg1, arg2) {
  return window['go']['main']['App']['GetThumb'](arg1, arg2);
}

export function ListImages(arg1) {
  return window['go']['main']['App']['ListImages'](arg1);
}

export function ListQueueTasks() {
  return window['go']['main']['App']['ListQueueTasks']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function PickSaveFile(arg1) {
  return window['go']['main']['App']['PickSaveFile'](arg1);
}

export function PrepareSubset(arg1) {
  return window['go']['main']['App']['PrepareSubset'](arg1);
}

export function RemoveQueueTask(arg1) {
  return window['go']['main']['App']['RemoveQueueTask'](arg1);
}

export function RetryQueueTask(arg1) {
  return window['go']['main']['App']['RetryQueueTask'](arg1);
}

export function SetDouyinCookie(arg1) {
  return window['go']['main']['App']['SetDouyinCookie'](arg1);
}

export function StartBatch(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartBatch'](arg1, arg2, arg3, arg4);
}

export function ZipDirectory(arg1) {
  return window['go']['main']['App']['ZipDirectory'](arg1);
}
