// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelBatch() {
  return window['go']['main']['App']['CancelBatch']();
}

export function CopyFile(arg1, arg2) {
  return window['go']['main']['App']['CopyFile'](arg1, arg2);
}

export function DetectURL(arg1) {
  return window['go']['main']['App']['DetectURL'](arg1);
}

export function DownloadSocial(arg1) {
  return window['go']['main']['App']['DownloadSocial'](arg1);
}

export function GetDouyinCookie() {
  return window['go']['main']['App']['GetDouyinCookie']();
}

export function GetImageBase64(arg1, arg2) {
  return window['go']['main']['App']['GetImageBase64'](arg1, arg2);
}

export function GetThumb(arg1, arg2) {
  return window['go']['main']['App']['GetThumb'](arg1, arg2);
}

export function ListImages(arg1) {
  return window['go']['main']['App']['ListImages'](arg1);
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function PickSaveFile(arg1) {
  return window['go']['main']['App']['PickSaveFile'](arg1);
}

export function PrepareSubset(arg1) {
  return window['go']['main']['App']['PrepareSubset'](arg1);
}

export function SetDouyinCookie(arg1) {
  return window['go']['main']['App']['SetDouyinCookie'](arg1);
}

export function StartBatch(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartBatch'](arg1, arg2, arg3);
}

export function ZipDirectory(arg1) {
  return window['go']['main']['App']['ZipDirectory'](arg1);
}
